name: Update Ons Price

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch gold price from goldprice.org
        run: |
          RESP=$(curl -s "https://data-asg.goldprice.org/dbXRates/USD")
          ONS=$(echo "$RESP" | sed -n 's/.*"xauPrice":\s*\([0-9.]*\).*/\1/p')

          if [ -z "$ONS" ]; then
            echo "{ \"gold\": null }" > api/ons.json
          else
            echo "{ \"gold\": $ONS }" > api/ons.json
          fi

      - name: Commit & Push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add api/ons.json
          git commit -m "Update ons price" || echo "No changes"
          git push
